name: Zotero Android CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Writing PSPDFKIT's key into a file to be then picked up by gradle.
        run: echo ${{secrets.PSPDFKIT_KEY}} | sed 's/./& /g' > pspdfkit-key.txt

      - name: Grant execute permission for bundle_translators.py
        run: chmod +x scripts/bundle_translators.py

      - name: Execute bundle_translators.py
        run: python3 scripts/bundle_translators.py

      - name: Grant execute permission for bundle_translation.py
        run: chmod +x scripts/bundle_translation.py

      - name: Execute bundle_translation.py
        run: python3 scripts/bundle_translation.py

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Download Android dependencies
        run: ./gradlew androidDependencies --no-configuration-cache

      - name: Generate dev build
        run: ./gradlew --no-configuration-cache -PpreDexLibs=false bundleDev --stacktrace
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-build
          path: |
            app/build/outputs/bundle/devDebug
